CREATE DATABASE IF NOT EXISTS stocks;

USE stocks;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(128) NOT NULL,
  PRIMARY KEY (id)
);


-- CREATE TABLE watchList(  
--   stock_id INT NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
--   id INT NOT NULL,
--   stock_name VARCHAR(128) NOT NULL,
--   FOREIGN KEY (id) REFERENCES users(id)
-- );