GET http://localhost:5000/users

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345678"
}

### Search API

GET https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=appl&apikey=process.env.STOCKS_API_KEY

### Test API

get https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=AACQ&apikey=env.process.STOCKS_API_KEY

### Delete later
get https://www.alphavantage.co/query?function=OVERVIEW&symbol=ALCO&apikey=env.process.STOCKS_API_KEY